diplodoc-platform/cli

src/index.ts
When copying, permissions for files and directories can be saved.
If the sources have read-only permission, an error occurs
when deleting excluded files.
=> DOCSTOOLS-291: add the write permission for files in the tmp folder

package-lock.json, package.json, src/constants.ts, src/index.ts, src/models.ts, src/resolvers/md2md.ts, src/services/tocs.ts, src/steps/processPages.ts, src/utils.ts
C флагом  --single-page собирается традиционная и одностраничная версия документации. Одностраничная версия будет лежать рядом с toc.yaml файлом в директории _single_page. Построение одностраничной версии происходит на этапе md2md. Производится исправление  якорей и добавление новых, исправление ссылок на другие md файлы, ccылок на ассеты и инклуды, понижение уровня заголовков. В результате, _single_page содержит index.md файл, полностью готовый для рендера в html, измененный toc.yaml и директории с ассетами и инклудами как они лежат в традиционной версии.  Новый toc.yaml содержит разделы с href не на файл, а на хеш на начало этой страницы в одностраничнике.  Эти хешы проставляются в плагины якорей в collect-функции плагина
Все преобразования md файлов выполняет yfm-transform в …
=> DOCSTOOLS-336: add support for one file mode

DOCS.md
A dash before the title and the section name break the assembly process.
=> Fix TOC syntax in the structure example

src/resolvers/md2html.ts
related issue: yandex-cloud/docs#310
lead to .html files instead of referencing .md files
=> fix(resolvers/md2html): fix overview page links

src/services/includers/batteries/openapi/generators/main.ts, src/services/includers/batteries/openapi/index.ts, src/services/includers/batteries/openapi/parsers.ts, src/services/includers/batteries/openapi/types.ts
Creating section for paths without tags.
Result example for merchant openapi:
=> fix(includers/openapi): openapi generator skips path without tags

src/services/includers/batteries/openapi/generators/endpoint.ts, src/services/includers/batteries/openapi/parsers.ts, src/services/includers/batteries/openapi/types.ts
preserve server description during Server object parsing
render server description inside the endpoint pages.
=> feat(includers/openapi): endpoint render server description

src/services/includers/batteries/openapi/constants.ts, src/services/includers/batteries/openapi/generators/main.ts, src/services/includers/batteries/openapi/generators/section.ts
get rid of the Description title on the leading pages
for the reason it being redundant and a waste of vertical space
=> fix(includers/openapi): delete Description title

src/services/includers/batteries/openapi/generators/main.ts
use appropriate title on the leading page when rendering untagged endpoints
=> fix(includers/openapi): appropriate leading page title

src/services/includers/batteries/openapi/generators/common.ts
move directive that disabled linting for the generated content towards end of the file
prevents failure of page title parsing
=> fix(includers/openapi): move disable lint directive

package-lock.json, package.json, src/services/includers/batteries/openapi/generators/endpoint.ts, src/services/includers/batteries/openapi/parsers.ts, src/services/includers/batteries/openapi/types.ts
render response status text on the endpoint page
=> fix(includers/openapi): response status text

src/services/includers/batteries/openapi/generators/traverse.ts
I corrected the references for such entities, because during the conversion, the allOf was lost, which determines the belonging to the model.
```
ScrollingPagerDTO:
description: Информация о страницах результатов.
type: object
allOf:
- $ref: '#/ForwardScrollingPagerDTO'
- properties:
prevPageToken:
description: Идентификатор предыдущей страницы результатов.
type: string
```
Before:
After:
=> Fix link with allOf property

src/services/includers/batteries/openapi/constants.ts, src/services/includers/batteries/openapi/generators/traverse.ts, src/services/includers/batteries/openapi/types.ts
I made a function for calculating the enum type:
- if there is a type, we take it
- if there is no type, check that it is an enum and take its type
=> Add default type for enum

src/services/includers/batteries/openapi/plugin/public/components/Response.tsx
handler for clicks on links in the viewer, external links are ignored and with the attribute data-router=off, the link to the blob is not external, therefore this attribute is needed
=> fix download link

src/services/includers/batteries/openapi/generators/traverse.ts
if the type is not specified and not enum, set the default value
before:
after:
Sample value:
```
properties:
code:
default: 200
```
=> add default type "object"

src/services/includers/batteries/openapi/generators/traverse.ts
enhance type inferring
strictly throw on unimplemented json schema 6 types
=> fix(includers/openapi): type inferring

src/models.ts, src/services/includers/batteries/unarchive.ts, src/services/includers/index.ts
includers are now to be specified as array using the full syntax
(even when using only one includer):
```
include:
path: <path-where-to-include>
includers:
- name: <includer-name-0>
<includer-parameter>: <value-for-includer-parameter>
- name: <includer-name-1>
<includer-parameter>: <value-for-includer-parameter>
```
BREAKING CHANGE: drop support for `includer` field inside include
drop support for specifying `includer` as name string
=> includers: drop includer field support

package-lock.json, package.json, src/cmd/xliff/compose.ts, src/cmd/xliff/constants.ts, src/cmd/xliff/extract.ts
[feat(cmd/xliff): extract xliff and skeleton](https://github.com/yandex-cloud/yfm-docs/commit/603d99075fd1e70c0ae649ea523843d9fa61921b) 
@diplodoc/markdown-translation integration to extract xliff and skeleton
[feat(cmd/xliff): compose xliff and skeleton into markdown](https://github.com/yandex-cloud/yfm-docs/commit/f9a4115f36da97f5f07cba8164749417c86a9738) 
@diplodoc/markdown-translation integration to compose xliff and
skeleton files into translated markdown
=> cmd/xliff: @diplodoc/markdown-translation integration

src/services/contributors.ts
Fix error, when yfm which running with "--contributors" flag looking for nested files using regexp by import, and found, that path not found.
=> fix(contributors): skip exception, when nested file not found

.github/dependabot.yml
use appropriate group as reviewers
=> infra: dependabot.yml reviewers

package-lock.json, package.json
update to latest markdown-translation version, that supports anchors
=> feat(cmd/xliff): @diplodoc/anchors syntax support

package-lock.json, package.json
update markdown-translation up to the version that supports @diplodoc/file syntax
=> feat(cmd/xliff): @diplodoc/file support

package-lock.json, package.json
Bumped OpenAPI extension plugin to [v1.2.6](https://github.com/diplodoc-platform/openapi-extension/releases/tag/v1.2.6)
=> fix: bump openapi version

package-lock.json, package.json
update markdown-translation up to the latest version, that supports @diplodoc/includes syntax and strikethrough
=> feat(cmd/xliff): diplodoc includes, strikethrough

src/cmd/build/index.ts, src/services/tocs.ts, src/steps/processPages.ts, src/utils/file.ts
With network storage shell.cp faster than copyFileSync
=> fix(copyFile): replace copyFileSync to shell.cp

src/constants.ts, src/steps/processPages.ts, src/vcs-connector/github.ts
When too many concurrency threads, requests may throw UND_ERR_CONNECT_TIMEOUT error.
=> fix(github): fix UND_ERR_CONNECT_TIMEOUT error

package-lock.json, package.json
- handle abbreviations that stick to non alphabet symbols
- handle liquid syntax inside inline code
- handle new note_content_open/close tokens
=> fix(cmd/xliff): update markdown-translation version

src/cmd/build/index.ts, src/models.ts
Add need-to-sanitize-html flag cause sometimes need to build without it
=> feat(cmd): add need-to-sanitize-html flag

src/commands/build/run.ts, src/globals.d.ts
Current CLI version is unable to copy files to a destination when building sources from another partition (e.g. a network drive). This PR addresses this by using `copyFile` with `COPYFILE_FICLONE`, preserving performance benefits of a hard link when possible; if a Copy-on-Write reflink is not applicable, it will create an exclusive copy using the fallback mechanism. See https://nodejs.org/api/fs.html#fspromisescopyfilesrc-dest-mode for more details.
=> Use `copyFile`'s Copy-on-Write optimizations instead of `link`

package-lock.json, package.json
Latest version of `cytoscape` breaks the installation of CLI: https://github.com/cytoscape/cytoscape.js/issues/3368#issuecomment-2839915605
This PR addresses that by pinning the version of `cytoscape`.
=> Pin cytoscape to 3.31.2

src/commands/build/features/changelogs/index.ts
Now each changelog from one file has filename in field source. But we doesn't want link after each changelog, we want one link for one file. And need full pathname for correct link to doc
=> Fix source to full path

package-lock.json, package.json, src/commands/build/features/output-html/utils.ts, src/commands/translate/run.ts, src/core/markdown/MarkdownService.ts, src/core/markdown/loader.ts, src/core/markdown/loader/resolve-no-translate.ts, tests/e2e/__snapshots__/translation.spec.ts.snap, tests/e2e/translation.spec.ts, tests/mocks/translation/no-translate/input/index.md, tests/mocks/translation/no-translate/input/no-translate.md, tests/mocks/translation/no-translate/input/openapi-spec.yaml, tests/mocks/translation/no-translate/input/toc.yaml
No-translate directive
Uses updated @diplodoc/translation with new directive 'no-translate' which allows to mark content as none translatable.
On build removes no-translating directive but leaves its content.
Examples:
Block directive
:::no-translate
Should not be translated.
Can use markup inside.
:::
Leaf directive
::no-translate [C:\Program Files\Application\config.ini]
::no-translate [~/Documents/project/src/main.rs]
Inline directive
:no-translate[GET /api/v1/users] — get all users
:no-translate[POST /api/v1/auth/login] — authorization
:no-translate[PUT /api/v1/users/{id}] — update users data
=> fix: rm no-translate directive, leave content

src/commands/build/features/output-html/plugins/images.ts
Disable prefix for class in svg
=> fix: disable prefix in svg classes

src/core/toc/loader.ts
Add warning, default empty string.
=> fix: empty href prop on filtered hook, add warning

src/core/toc/__snapshots__/index.spec.ts.snap, src/core/toc/index.spec.ts, src/core/toc/loader.ts, tests/e2e/errors.spec.ts, tests/mocks/errors/object-validation/input/index.md, tests/mocks/errors/object-validation/input/toc.yaml
Such designs lead to a correct build, but then crashes when try render.
Adding verification and build failure
```yaml
...
- name: {{some_var}}
...
- items: {{some_var}}
...
```
=> fix: incorrect vars in toc
