package-lock.json
package.json

Add support multiple anchors to a header

update: @doc-tools/transform up to 1.1.0

---

src/steps/processExcludedFiles.ts

Bug was fixed

---

src/steps/publishFiles.ts
src/validator.ts

Необходимо иметь возможность загружать файлы в корень бакета S3

Make S3 storage prefix optional

---

src/app/interceptors/leading-page-links.js

* nested urls were fixed.
* Comments were fixed

Nested urls were fixed. 

---

README.md
README.ru.md
src/resolvers/md2md.ts

Up version yfm-transform
Merge PR after - https://github.com/yandex-cloud/yfm-transform/pull/36

Readme was updated (CLOUDFRONT-5273: Механика контент-программы)

---

src/app/components/App/App.tsx
src/app/utils.ts
src/utils.ts

При изменении viewport'а применяем стили для мобильной верстки

Handle responsive view on page resize

---

src/constants.ts
src/vcs-connector/github.ts

1. Fix issues with vcs connector.
2. Update constants

Fix issues with vcs connector.

---

src/constants.ts
src/index.ts
src/validator.ts

Делаем валидацию файла с редиректами + перекладываем при md2md

DOCSTOOLS-344: support redirects

---

src/resolvers/md2html.ts
src/resolvers/md2md.ts
src/services/leading.ts
src/services/preset.ts
src/services/tocs.ts
src/utils.ts

This reverts commit 89de56785f716c5054dd2a9c0b238d50dee607ed, reversing
changes made to fa140d11ad897265acaf36794afa60f3669276d6.

CLOUDFRONT-7153 Revert deep merge

---

src/index.ts
src/steps/processServiceFiles.ts

Logs errors were added for catching errors during processing services

---

src/services/metadata.ts

https://st.yandex-team.ru/CLOUDFRONT-8744

Fixed logic with reading metadata

---

src/index.ts
src/models.ts
src/steps/processExcludedFiles.ts
src/steps/processMapFile.ts
src/steps/processServiceFiles.ts
tests/e2e/generate-map.spec.ts
tests/mocks/generate-map/test1/expected-output/files.json
tests/mocks/generate-map/test1/input/ru/folder1/a1.md
tests/mocks/generate-map/test1/input/ru/folder1/folder2/a1.md
tests/mocks/generate-map/test1/input/ru/folder1/folder2/toc.yaml
tests/mocks/generate-map/test1/input/ru/folder1/toc.yaml
tests/mocks/generate-map/test1/input/ru/toc.yaml
tests/mocks/generate-map/test2/expected-output/files.json
tests/mocks/generate-map/test2/input/en/toc.yaml
tests/mocks/generate-map/test2/input/ru/toc.yaml
tests/utils.ts

1. Added a flag that allows you to generate files.json, which has a list of all paths in the document.
2. Upload .yfm file to s3 while md2md

[DOCSTOOLS-711, DOCSTOOLS-763, DOCSTOOLS-713]

---

src/services/includers/batteries/openapi/index.ts
src/services/tocs.ts

apply includers recursively
apply includers correct toc paths

docstools-1142 fix(includers): apply includers recursively, correct paths inside processed toc

---

src/services/leading.ts
src/services/tocs.ts
src/services/utils.ts
tests/units/services/utils.test.ts

Add conditions and substitutions support in title, description, meta.title, links[*].title, links[*].description and toc.title

feat: add conditions and substitutions in title, desc

---

src/cmd/xliff/compose.ts
src/cmd/xliff/extract.ts

xliff extract/compose improve info and error logging

docstools-1411 xliff extract compose error reporting

---

webpack.config.js

exclusion of the external dependencies from build
improves bundle size

infra: exclude external dependencies from build

---

.env.template
package-lock.json
package.json
webpack.config.js

exclude external dependencies from build
leads to ~two fold build time decrease

chore(build): add dev build target

---

README.md
README.ru.md
package-lock.json
package.json
src/index.ts
src/models.ts
src/resolvers/md2html.ts
src/services/metadata.ts
src/services/plugins.ts
src/services/tocs.ts
src/steps/publishFilesToS3.ts
src/validator.ts
tests/integrations/services/metadataAuthors.test.ts
tests/integrations/services/metadataContributors.test.ts
tests/units/services/metadata.test.ts
tsconfig.json

Ability to debug source .ts code through ts-node

Debug through ts-node

---

src/models.ts
src/services/includers/batteries/generic.ts
src/services/includers/batteries/index.ts
src/services/includers/batteries/openapi/index.ts
src/services/includers/batteries/sourcedocs.ts
src/services/includers/index.ts

introduce new includer - generic includer
includes folder with markdown content
soft deprication of the sourcedocs includer in favor of the generic one

feat(includers/generic): include markdown content

---

src/models.ts
src/services/includers/batteries/generic.ts
src/services/includers/batteries/openapi/index.ts
src/services/includers/index.ts

pass parameters into consecutive applied includer

feat(services/includers): pass params between includers

---

src/app/interceptors/leading-page-links.js

fix(interceptors): intercept links without extension

---

src/services/includers/batteries/openapi/generators/traverse.ts

fix(includers/openapi): no default values in description

---

src/services/includers/batteries/openapi/generators/traverse.ts

fix(includers/openapi): undefined[] fix

---

src/services/includers/batteries/openapi/generators/traverse.ts

fix(includers/openapi): no nulls in samples

---

src/services/includers/batteries/openapi/generators/traverse.ts

This reverts commit e5c82cb0a468aec3993fcb7d73a0e0864514e64f.

Revert "fix(includers/openapi): ref with custom description fix"

---

src/services/includers/batteries/openapi/generators/endpoint.ts

display schema type of the requests and responses

fix(includers/openapi): display req/res schema type

---

src/services/includers/batteries/openapi/generators/traverse.ts

fix(includers/openapi): ref with custom description fix (2nd try)

---

package-lock.json
package.json

changes:
https://github.com/yandex-cloud/yfm2xliff/pull/18
https://github.com/yandex-cloud/yfm2xliff/pull/17

fix(cmd/yfm2xliff): update to newer lib version

---

src/services/includers/batteries/openapi/generators/traverse.ts

allOf merge bug: mutation of source schema lead to excess properties of objects

fix(includers/openapi): excess properties in allOf

---

src/services/includers/batteries/openapi/generators/endpoint.ts
src/services/includers/batteries/openapi/generators/traverse.ts

fix(includers/openapi): table for enums

---

src/services/includers/batteries/common.ts
src/services/includers/batteries/openapi/generators/endpoint.ts
src/services/includers/batteries/openapi/generators/traverse.ts
src/services/includers/batteries/openapi/types.ts

fix undefiened & default values

fix(includers/openapi): default value in query

---

src/services/includers/batteries/openapi/generators/traverse.ts

fix(includers/openapi): array of enum description fix

---

src/services/includers/batteries/openapi/generators/endpoint.ts
src/services/includers/batteries/openapi/generators/traverse.ts

fix(includers/openapi): some enums are not printed in separate tables

---

src/services/includers/batteries/openapi/constants.ts
src/services/includers/batteries/openapi/generators/endpoint.ts

add view for primitive body

---

src/models.ts
src/services/includers/batteries/generic.ts
src/services/includers/batteries/openapi/constants.ts
src/services/includers/batteries/openapi/generators/common.ts
src/services/includers/batteries/openapi/generators/endpoint.ts
src/services/includers/batteries/openapi/index.ts
src/services/includers/batteries/openapi/types.ts
src/services/includers/batteries/openapi/utils.ts
src/services/includers/batteries/sourcedocs.ts
src/services/includers/batteries/unarchive.ts
src/services/includers/index.ts
src/services/tocs.ts

- Add `filter` flag in toc
- Add `noindex` flag in toc
- Add `leadingPage.mode` flag to configure Overview section placement

Improve openapi filtering

---

src/constants.ts
src/models.ts
src/services/authors.ts
src/services/metadata.ts
src/services/utils.ts
src/utils/markup.ts
src/vcs-connector/connector-models.ts
src/vcs-connector/github.ts
tests/integrations/services/metadataContributors.test.ts
tests/units/services/authors.test.ts

Reverts yandex-cloud/yfm-docs#312

Revert "feat: get file author from github"

---

package-lock.json
package.json

update @diplodoc/markdown-translation package
add support for notes plugin

feat(cmd/xliff): notes plugin support

---

src/services/includers/batteries/openapi/generators/traverse.ts

openapi schema sample:
```
extensions:
allOf:
- $ref: '#/components/schemas/OrderExtensions'
default: null
description: Дополнительные параметры для оформления оффлайн заказа
```
Before:
After:

fix(includers/openapi): add description for allOf item

---

.github/dependabot.yml

configure dependabot to check for dependencies daily

infra: dependabot.yml

---

package-lock.json
package.json

add support for:
- diplodoc cuts
- gfm tables

feat(cmd/xliff): dipldodoc cuts, gfm tables

---

package-lock.json
package.json

update markdown-translation version up to version that supports @diplodoc/imsize plugin

feat(cmd/xliff): @diplodoc/imsize support

---

package-lock.json
package.json
src/resolvers/md2md.ts

- bumb transform version with code block fix in liquid
- pass conditionsInCode arg to liquid when build project with --output-format md

Fix cycles in code blocks

---

package-lock.json
package.json

update markdown-translation to version that supports ref links.

feat(cmd/xliff): @diplodoc/links ref links {#T}

---

package-lock.json
package.json

1. Openapi v1.2.8, see [changelog](https://github.com/diplodoc-platform/openapi-extension/releases/tag/v1.2.8)

fix(openapi): bump version

---

package-lock.json
package.json

OpenAPI plugin [v1.2.9](https://github.com/diplodoc-platform/openapi-extension/releases/tag/v1.2.9)

fix: bump openapi version

---

src/vcs-connector/client/github.ts

feat: change a log level while a request to github failed because a commit not found

---

package-lock.json
package.json

chore: update @diplodoc/client package

---

package-lock.json
package.json

[BETA] improved inline segmentation for syntax:
- links
- bold
- italics
- strikethrough
- superscript
- monospace
- inline code

feat(cmd/xliff): improved inline segmentation beta

---

package-lock.json
package.json

fix(cmd/xliff): inline segmentation variables, liquid

---

package-lock.json
package.json

- support nested tabs
- fix inline segmentation bugs
- support tab groups

feat(cmd/xliff): update markdown-translation

---

schemas/toc-schema.yaml

addition to:
https://github.com/diplodoc-platform/components/pull/246

feat: add label

---

src/commands/publish/run.ts

logger pass two args
https://github.com/diplodoc-platform/cli/blob/master/src/logger/index.ts#L128

fix: upload logs

---

package-lock.json
package.json

chore(deps): update @diplodoc/client 3.1.8 -> 3.1.9

---

src/commands/build/features/html/index.ts
src/commands/build/index.ts
src/core/toc/TocService.ts
src/core/toc/hooks.ts
src/core/toc/index.spec.ts
src/pages/document.ts
src/resolvers/md2html.ts
src/services/search.ts
src/steps/processPages.ts

- **fix: Add hash to search index files**
- **fix: Fix NavPanel highlite for static content generation**

Fix search cache

---

package-lock.json
package.json

feat: bump transform version

---

package-lock.json
package.json
src/commands/translate/commands/extract.ts
src/commands/translate/config.ts
src/commands/translate/utils/fs.ts

feat: add --schema param to translate extract command

---

src/core/toc/TocService.ts

fix: remove unpack from TocService.dir

---

package-lock.json
package.json
src/commands/publish/run.ts

- **feat: use lib-storage instead of direct s3 upload**
- **fix: update axios to a secure version**

Fix S3 upload

---

src/commands/build/features/singlepage/index.ts
src/commands/build/hooks.ts
src/commands/build/index.ts
src/commands/build/types.ts

This reverts commit ddc212f26a84c0098e9646ae9bfe9854bbb29231.

fix: revert Fix singlepage files race condition

---

src/core/toc/TocService.ts

feat: add toc dump cache

---

.github/workflows/ci.yml

chore: release 4.57.12

---

src/commands/translate/utils/config.ts

fix: translate all files if no toc.yaml

---

src/commands/translate/run.ts
src/commands/translate/utils/config.ts

Compose fix

---

src/commands/translate/commands/extract.ts
src/commands/translate/index.ts
src/commands/translate/run.ts
src/commands/translate/utils/config.ts
src/core/vars/VarsService.ts

fix: ts translate command errors

---

src/commands/build/index.spec.ts
src/commands/build/index.ts
src/index.ts

fix: rm strict false mode

---

src/extensions/search/provider.ts

fix: add api prop to config

---

src/commands/build/features/output-html/plugins/includes-detect.ts
src/commands/build/features/output-html/plugins/includes.ts
src/commands/build/features/output-html/plugins/links.ts
src/commands/build/features/output-html/utils.ts

fix: check md link files

---

src/commands/build/index.ts
tests/e2e/__snapshots__/regression.test.ts.snap
tests/mocks/regression/input/generic/3.md

fix: generic include

---

src/commands/build/features/changelogs/collect.ts
src/commands/build/features/changelogs/index.ts
src/steps/processChangelogs.ts

Fix build changelogs
Fix path for collect changelogs to one file
Fix clear state for changelogs from different paths
None

Fix create changelogs

---

src/commands/translate/run.ts
tests/e2e/translation.spec.ts

fix: temp disable toc filtrations

---

tests/package-lock.json
tests/package.json

deps: update @diplodoc/client@3.6.3 to run tests

---

src/commands/build/features/changelogs/collect.ts
src/commands/build/features/changelogs/index.ts

Fix build changelogs for big project

Fix changelogs for big project

---

.github/workflows/package-lock.yaml
package.json

temporary fix
https://github.com/nodejs/undici/issues/4372
bug at line
https://github.com/nodejs/undici/commit/177ca1bf58b453a9f8cbf59613ab183763d34794#diff-21281b9594153dea4aea7e7b1ea259aad03cbedd12ea5d4ad8076855add66a91L512
not support node 18+

fix: build_doc fixed undici version

---

src/extensions/mdit-plugins/index.ts

Текущее расширение `mdit-plugins` содержит в себе ряд недостатков, которые не позволяют реализовать весь потенциал данного расширения! А именно:
- Отсутствует поддержка именованного экспорта, далеко не все плагины использует подход `module.export = fn`
- Совмещение на том же уровне настроек расширений в `yfm` с настройками самого плагина приводит к коллизиям имён. Например у плагина может быть опция `name`, но она зарезервирована самим `mdit-plugins`
- Нет никакой возможности используя `mdit-plugins` сконфигурировать плагин с не примитивными опциями, т.к. в `yfm` функцию не объявишь
```ts
name: string;  // Название совместимого markdown-it плагина
exportName?: string; // название используемого экспорта из module.export
options?: Hash; // Опции плагина
resolver?: string; // путь к файлу …
```

feat: Improve mdit_plugins

---

src/core/markdown/__snapshots__/loader.spec.ts.snap
src/core/markdown/loader.spec.ts
src/core/markdown/loader.ts
src/core/markdown/loader/resolve-assets.ts
src/core/markdown/loader/resolve-code.ts
src/core/markdown/types.ts
src/core/markdown/utils.ts

- detect codeblocks
- detect reference assets for image
- extend image assets for fields: subtype, code

Resolve-codeblock

---

src/commands/build/features/output-md/index.ts
src/commands/build/features/output-md/plugins/merge-autotitles.ts
src/core/markdown/utils.ts
tests/e2e/__snapshots__/preprocess.test.ts.snap
tests/mocks/preprocess/input/autotitle.md

fix: support reference links in autotitles
fix: incorrect rebased

fix: support reference links in autotitles

---

src/commands/build/features/pdf-page/index.spec.ts
src/commands/build/features/pdf-page/index.ts
src/commands/build/features/pdf-page/utils.ts
src/commands/build/features/singlepage/index.ts
src/commands/build/types.ts
tests/e2e/__snapshots__/pdf-page.spec.ts.snap
tests/e2e/pdf-page.spec.ts
tests/mocks/pdf-page/input/.yfm
tests/mocks/pdf-page/input/page2.md

Literally we copied whole single-page feature with utils.
Then we slightly changed some parts of this feature to prepare specific html/json files for further pdf generation.
Final goal is to move pdf feature to separate extension, for now it's somewhere in the middle of this process.

fix: pdf link
